env:
  browser: true
  commonjs: true
  es2021: true
parser:
  'vue-eslint-parser'
plugins:
  - '@typescript-eslint'
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:vue/vue3-recommended'
  - 'prettier'
parserOptions:
  parser: '@typescript-eslint/parser'
  extraFileExtensions:
    - .vue
  ecmaVersion: 12
rules: 
  indent: ['error', 2, { SwitchCase: 1 }]
  linebreak-style: ['warn', 'windows']
  quotes: ['error', 'single']
  semi: ['error', 'never']
globals:
  mw: writeable