import { MockMwMap } from './mockMwGlobal.js'

export const MOCK_MW_CONFIGS = {
  wgBreakFrames: true,
  wgSeparatorTransformTable: ['', ''],
  wgDigitTransformTable: ['', ''],
  wgDefaultDateFormat: 'zh',
  wgMonthNames: [
    '',
    '1月',
    '2月',
    '3月',
    '4月',
    '5月',
    '6月',
    '7月',
    '8月',
    '9月',
    '10月',
    '11月',
    '12月',
  ],
  wgRequestId: 'bd22385b2a95f9b27df2af4b',
  wgCanonicalNamespace: '',
  wgCanonicalSpecialPageName: false,
  wgNamespaceNumber: 0,
  wgPageName: 'Example',
  wgTitle: 'Example',
  wgCurRevisionId: 23344,
  wgRevisionId: 0,
  wgArticleId: 4552,
  wgIsArticle: false,
  wgIsRedirect: false,
  wgAction: 'history',
  wgUserName: '机智的小鱼君',
  wgUserGroups: [
    'checkuser',
    'interface-admin',
    'staff',
    'suppress',
    'sysop',
    'widgeteditor',
    '*',
    'user',
    'autoconfirmed',
  ],
  wgCategories: [],
  wgPageViewLanguage: 'zh',
  wgPageContentLanguage: 'zh',
  wgPageContentModel: 'wikitext',
  wgRelevantPageName: 'Example',
  wgRelevantArticleId: 4552,
  wgUserId: 316917,
  wgUserIsTemp: false,
  wgUserEditCount: 899,
  wgUserRegistration: 1494166480000,
  wgUserFirstRegistration: 1494166480000,
  wgUserVariant: 'zh',
  wgIsProbablyEditable: true,
  wgRelevantPageIsProbablyEditable: true,
  wgRestrictionEdit: [],
  wgRestrictionMove: [],
  wgCiteReferencePreviewsActive: true,
  wgMediaViewerOnClick: true,
  wgMediaViewerEnabledByDefault: true,
  wgPopupsFlags: 0,
  wgVisualEditor: {
    pageLanguageCode: 'zh',
    pageLanguageDir: 'ltr',
    pageVariantFallbacks: [
      'zh-hans',
      'zh-hant',
      'zh-cn',
      'zh-tw',
      'zh-hk',
      'zh-sg',
      'zh-mo',
      'zh-my',
    ],
  },
  'thanks-confirmation-required': true,
  wgRelatedArticlesCompat: [],
  'ext.avatar.current_user.url':
    'https://storage.moegirl.org.cn/moegirl-dev/avatars/316917/latest.png',
  'ext.avatar.current_user.thumb_url':
    'https://storage.moegirl.org.cn/moegirl-dev/avatars/316917/latest.png!avatar.thumb',
  wgCheckUserClientHintsHeadersJsApi: [
    'architecture',
    'bitness',
    'brands',
    'fullVersionList',
    'mobile',
    'model',
    'platform',
    'platformVersion',
  ],
  wgCheckUserTemporaryAccountMaxAge: 86400,
  wgMoeAuthConfig: {
    endpoint: 'https://app.moegirl.org.cn/moe-auth/',
    specialHijackMap: {
      ChangeCredentials: ['更改凭据', '變更憑證', 'ChangeCredentials'],
      ChangePassword: [
        '修改密码',
        '修改密碼',
        '修改密码',
        '重置密码',
        '找回密码',
        '變更密碼',
        '修改密碼',
        '密碼重設',
        'ChangePassword',
        'ResetPass',
        'ResetPassword',
      ],
      CreateAccount: [
        '创建账户',
        '創建賬戶',
        '建立帳戶',
        '建立帳號',
        '建立帐号',
        '创建账户',
        '建立帳號',
        '建立帳戶',
        '建立帳號',
        'CreateAccount',
      ],
      Userlogin: [
        '用户登录',
        '用戶登入',
        '使用者登入',
        '用户登录',
        '登录',
        '使用者登入',
        'UserLogin',
        'Login',
      ],
    },
  },
  wgEditSubmitButtonLabelPublish: false,
  wgEchoSeenTime: {
    alert: '1970-01-01T00:00:01Z',
    notice: '1970-01-01T00:00:01Z',
  },
  wgBackendResponseTime: 550,
  wgPageParseReport: {
    limitreport: {
      cputime: '0.003',
      walltime: '0.003',
      ppvisitednodes: {
        value: 9,
        limit: 1000000,
      },
      postexpandincludesize: {
        value: 15,
        limit: 2097152,
      },
      templateargumentsize: {
        value: 0,
        limit: 2097152,
      },
      expansiondepth: {
        value: 2,
        limit: 100,
      },
      expensivefunctioncount: {
        value: 0,
        limit: 50,
      },
      'unstrip-depth': {
        value: 0,
        limit: 20,
      },
      'unstrip-size': {
        value: 0,
        limit: 5000000,
      },
      timingprofile: ['100.00%    0.000      1 -total'],
    },
    cachereport: {
      timestamp: '20251023070258',
      ttl: 2592000,
      transientcontent: false,
    },
  },
  debug: 0,
  skin: 'moeskin',
  stylepath: '/skins',
  wgArticlePath: '/$1',
  wgScriptPath: '',
  wgScript: '/index.php',
  wgSearchType: 'CirrusSearch',
  wgVariantArticlePath: '/$2/$1',
  wgServer: 'http://localhost:8000',
  wgServerName: 'localhost',
  wgUserLanguage: 'zh',
  wgContentLanguage: 'zh',
  wgVersion: '1.43.3',
  wgFormattedNamespaces: {
    '0': '',
    '1': 'Talk',
    '2': 'User',
    '3': 'User talk',
    '4': '萌娘百科',
    '5': '萌娘百科 talk',
    '6': 'File',
    '7': 'File talk',
    '8': 'MediaWiki',
    '9': 'MediaWiki talk',
    '10': 'Template',
    '11': 'Template talk',
    '12': 'Help',
    '13': 'Help talk',
    '14': 'Category',
    '15': 'Category talk',
    '274': 'Widget',
    '275': 'Widget talk',
    '710': 'TimedText',
    '711': 'TimedText talk',
    '828': 'Module',
    '829': 'Module talk',
    '-2': 'Media',
    '-1': 'Special',
  },
  wgNamespaceIds: {
    media: -2,
    special: -1,
    '': 0,
    talk: 1,
    user: 2,
    user_talk: 3,
    萌娘百科: 4,
    萌娘百科_talk: 5,
    file: 6,
    file_talk: 7,
    mediawiki: 8,
    mediawiki_talk: 9,
    template: 10,
    template_talk: 11,
    help: 12,
    help_talk: 13,
    category: 14,
    category_talk: 15,
    widget: 274,
    widget_talk: 275,
    timedtext: 710,
    timedtext_talk: 711,
    module: 828,
    module_talk: 829,
    模块: 828,
    模组: 828,
    模块对话: 829,
    模块讨论: 829,
    模组对话: 829,
    模组讨论: 829,
    微件: 274,
    小部件: 274,
    小组件: 274,
    小元件: 274,
    微件讨论: 275,
    小部件讨论: 275,
    小组件讨论: 275,
    小元件讨论: 275,
    媒体: -2,
    媒体文件: -2,
    媒体档案: -2,
    特殊: -1,
    讨论: 1,
    对话: 1,
    用户: 2,
    用户讨论: 3,
    用户对话: 3,
    使用者讨论: 3,
    使用者对话: 3,
    专案: 4,
    image: 6,
    文件: 6,
    档案: 6,
    图像: 6,
    图片: 6,
    image_talk: 7,
    文件讨论: 7,
    文件对话: 7,
    档案讨论: 7,
    档案对话: 7,
    图像讨论: 7,
    图像对话: 7,
    图片讨论: 7,
    模板: 10,
    样板: 10,
    模板讨论: 11,
    模板对话: 11,
    样板讨论: 11,
    样板对话: 11,
    帮助: 12,
    说明: 12,
    使用说明: 12,
    帮助讨论: 13,
    帮助对话: 13,
    说明讨论: 13,
    使用说明讨论: 13,
    分类: 14,
    分类讨论: 15,
    分类对话: 15,
    模組: 828,
    模塊: 828,
    模組對話: 829,
    模組討論: 829,
    模塊對話: 829,
    模塊討論: 829,
    小組件: 274,
    微件討論: 275,
    小元件討論: 275,
    小部件討論: 275,
    小組件討論: 275,
    媒體: -2,
    媒體檔案: -2,
    媒體文件: -2,
    討論: 1,
    對話: 1,
    使用者: 2,
    用戶: 2,
    使用者討論: 3,
    使用者對話: 3,
    用戶討論: 3,
    用戶對話: 3,
    專案: 4,
    檔案: 6,
    圖像: 6,
    圖片: 6,
    檔案討論: 7,
    檔案對話: 7,
    文件討論: 7,
    文件對話: 7,
    圖像討論: 7,
    圖像對話: 7,
    圖片討論: 7,
    樣板: 10,
    模板討論: 11,
    模板對話: 11,
    樣板討論: 11,
    樣板對話: 11,
    說明: 12,
    幫助: 12,
    使用說明: 12,
    說明討論: 13,
    幫助討論: 13,
    幫助對話: 13,
    使用說明討論: 13,
    分類: 14,
    分類討論: 15,
    分類對話: 15,
    萌娘百科讨论: 5,
    萌娘百科对话: 5,
    专案讨论: 5,
    萌娘百科討論: 5,
    萌娘百科對話: 5,
    專案討論: 5,
    mediawiki讨论: 9,
    'timedtext talk': 711,
    mediawiki討論: 9,
    project: 4,
    project_talk: 5,
  },
  wgContentNamespaces: [0],
  wgSiteName: '萌娘百科',
  wgDBname: 'enmoegirl',
  wgWikiID: 'enmoegirl',
  wgCaseSensitiveNamespaces: [],
  wgCommentCodePointLimit: 500,
  wgExtensionAssetsPath: '/extensions',
  wgUrlProtocols:
    'bitcoin\\:|ftp\\:\\/\\/|ftps\\:\\/\\/|geo\\:|git\\:\\/\\/|gopher\\:\\/\\/|http\\:\\/\\/|https\\:\\/\\/|irc\\:\\/\\/|ircs\\:\\/\\/|magnet\\:|mailto\\:|matrix\\:|mms\\:\\/\\/|news\\:|nntp\\:\\/\\/|redis\\:\\/\\/|sftp\\:\\/\\/|sip\\:|sips\\:|sms\\:|ssh\\:\\/\\/|svn\\:\\/\\/|tel\\:|telnet\\:\\/\\/|urn\\:|worldwind\\:\\/\\/|xmpp\\:|\\/\\/',
  wgActionPaths: {},
  wgTranslateNumerals: true,
  wgExtraSignatureNamespaces: [],
  wgLegalTitleChars: ' %!"$&\'()*,\\-./0-9:;=?@A-Z\\\\\\^_`a-z~+\\u0080-\\uFFFF',
  wgIllegalFileChars: ':/\\\\',
  wgCiteVisualEditorOtherGroup: false,
  wgCiteResponsiveReferences: true,
  wgCiteBookReferencing: false,
  wgCodeMirrorLineNumberingNamespaces: null,
  wgMathEntitySelectorUrl: 'https://www.wikidata.org/w/api.php',
  wgMediaViewer: true,
  wgPopupsVirtualPageViews: false,
  wgPopupsGateway: 'mwApiPlain',
  wgPopupsRestGatewayEndpoint: '/api/rest_v1/page/summary/',
  wgPopupsStatsvSamplingRate: 0,
  wgPopupsTextExtractsIntroOnly: true,
  wgRelatedArticlesCardLimit: 5,
  wgVisualEditorConfig: {
    usePageImages: true,
    usePageDescriptions: false,
    isBeta: false,
    disableForAnons: false,
    preloadModules: ['site', 'user'],
    namespaces: [0, 2, 6, 14],
    contentModels: {
      wikitext: 'article',
    },
    pluginModules: [
      'ext.abuseFilter.visualEditor',
      'ext.cite.visualEditor',
      'ext.CodeMirror.visualEditor.init',
      'ext.disambiguator.visualEditor',
      'ext.math.visualEditor',
      'ext.spamBlacklist.visualEditor',
      'ext.geshi.visualEditor',
      'ext.templateDataGenerator.editPage',
      'ext.TemplateSandbox.visualeditor',
      'ext.titleblacklist.visualEditor',
    ],
    thumbLimits: [120, 150, 180, 200, 250, 300],
    galleryOptions: {
      imagesPerRow: 0,
      imageWidth: 120,
      imageHeight: 120,
      captionLength: true,
      showBytes: true,
      showDimensions: true,
      mode: 'traditional',
    },
    tabPosition: 'before',
    tabMessages: {
      editsource: 'visualeditor-ca-editsource',
      createsource: 'visualeditor-ca-createsource',
      editlocaldescriptionsource: 'visualeditor-ca-editlocaldescriptionsource',
      createlocaldescriptionsource: 'visualeditor-ca-createlocaldescriptionsource',
      editsection: 'editsection',
      editsectionhint: 'editsectionhint',
      editsectionsource: 'visualeditor-ca-editsource-section',
      editsectionsourcehint: 'visualeditor-ca-editsource-section-hint',
    },
    singleEditTab: false,
    enableVisualSectionEditing: 'mobile',
    showBetaWelcome: true,
    allowExternalLinkPaste: false,
    enableHelpCompletion: true,
    enableTocWidget: false,
    enableWikitext: true,
    useChangeTagging: true,
    editCheckTagging: false,
    editCheck: false,
    editCheckABTest: false,
    editCheckReliabilityAvailable: true,
    namespacesWithSubpages: [1, 2, 3, 4, 5, 7, 8, 9, 10, 11, 12, 13, 15, 0, 828, 829, 275],
    specialBooksources: 'Special:网络书源',
    rebaserUrl: false,
    feedbackApiUrl: false,
    feedbackTitle: false,
    sourceFeedbackTitle: false,
    transclusionDialogNewSidebar: true,
    cirrusSearchLookup: true,
    defaultSortPrefix: 'DEFAULTSORT',
  },
  wgCirrusSearchFeedbackLink: false,
  wgPopupsConflictsWithNavPopupGadget: false,
  wgCiteReferencePreviewsVisible: true,
}

export const useMockMwConfig = () => {
  return new MockMwMap(MOCK_MW_CONFIGS)
}
