/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ActionButton: typeof import('./components/ActionButton')['ActionButton']
  const BasePlugin: typeof import('@/plugins/BasePlugin')['default']
  const CheckBox: typeof import('./components/CheckBox')['CheckBox']
  const Endpoints: typeof import('./constants/endpoints')['Endpoints']
  const InputBox: typeof import('./components/InputBox')['InputBox']
  const ProgressBar: typeof import('./components/ProgressBar/index')['ProgressBar']
  const RadioBox: typeof import('./components/RadioBox')['RadioBox']
  const RegisterPreferences: typeof import('./decorators/Preferences')['RegisterPreferences']
  const TabContent: typeof import('./components/TabView/TabView')['TabContent']
  const TabLabel: typeof import('./components/TabView/TabView')['TabLabel']
  const TabView: typeof import('./components/TabView/TabView')['TabView']
  const TwinSwapInput: typeof import('./components/TwinSwapInput/index')['TwinSwapInput']
  const camelCase: typeof import('./utils/string')['camelCase']
  const capitalize: typeof import('./utils/string')['capitalize']
  const checkURL: typeof import('./utils/schemaValidator')['checkURL']
  const deepToRaw: typeof import('./utils/vueReactivity')['deepToRaw']
  const defineAsyncPlugin: typeof import('./utils/defineAsyncPlugin')['defineAsyncPlugin']
  const ensureSlash: typeof import('./utils/string')['ensureSlash']
  const noop: typeof import('./utils/noop')['noop']
  const openLinkPreview: typeof import('./utils/schemaValidator')['openLinkPreview']
  const paramCase: typeof import('./utils/string')['paramCase']
  const promiseWithResolvers: typeof import('./polyfills/Promise.withResolvers')['promiseWithResolvers']
  const schemaValidator: typeof import('./utils/schemaValidator')['schemaValidator']
  const sleep: typeof import('./utils/sleep')['sleep']
  const snakeCase: typeof import('./utils/string')['snakeCase']
  const trimSlash: typeof import('./utils/string')['trimSlash']
  const uncapitalize: typeof import('./utils/string')['uncapitalize']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { CheckBoxProps } from './components/CheckBox'
  import('./components/CheckBox')
  // @ts-ignore
  export type { InputBoxProps } from './components/InputBox'
  import('./components/InputBox')
  // @ts-ignore
  export type { RadioBoxProps } from './components/RadioBox'
  import('./components/RadioBox')
  // @ts-ignore
  export type { TabViewLabelOptions } from './components/TabView/TabView'
  import('./components/TabView/TabView')
  // @ts-ignore
  export type { TwinSwapInputProps, TwinSwapInputInput, TwinSwapElement } from './components/TwinSwapInput/index'
  import('./components/TwinSwapInput/index')
  // @ts-ignore
  export type { Endpoints } from './constants/endpoints'
  import('./constants/endpoints')
  // @ts-ignore
  export type { PreferenceAugmented } from './decorators/Preferences'
  import('./decorators/Preferences')
}
