/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ActionButton: typeof import('./components/ActionButton')['ActionButton']
  const BasePlugin: typeof import('@/plugins/BasePlugin')['default']
  const CheckBox: typeof import('./components/CheckBox')['CheckBox']
  const Endpoints: typeof import('./constants/endpoints')['Endpoints']
  const ProgressBar: typeof import('./components/ProgressBar')['ProgressBar']
  const RadioBox: typeof import('./components/RadioBox')['RadioBox']
  const camelCase: typeof import('./utils/string')['camelCase']
  const capitalize: typeof import('./utils/string')['capitalize']
  const defineAsyncPlugin: typeof import('./utils/defineAsyncPlugin')['defineAsyncPlugin']
  const ensureSlash: typeof import('./utils/string')['ensureSlash']
  const noop: typeof import('./utils/noop')['noop']
  const paramCase: typeof import('./utils/string')['paramCase']
  const promiseWithResolvers: typeof import('./polyfills/Promise.withResolvers')['promiseWithResolvers']
  const setProgressBarToComplete: typeof import('./components/ProgressBar')['setProgressBarToComplete']
  const sleep: typeof import('./utils/sleep')['sleep']
  const snakeCase: typeof import('./utils/string')['snakeCase']
  const trimSlash: typeof import('./utils/string')['trimSlash']
  const uncapitalize: typeof import('./utils/string')['uncapitalize']
  const version: typeof import('./constants/version')['default']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Endpoints } from './constants/endpoints'
  import('./constants/endpoints')
}
