name: Release Notes

on:
  push:
    tags:
      - '*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: false
          generate_release_notes: true
